site_name: afq-docs
nav:
- Home: 'index.md'
- Bibliography:
    - 'Diffusion MRI': 'bibliography/diffusion-mri.md'
    - 'Machine learning': 'bibliography/machine-learning.md'
- About:
    - 'License': 'about/license.md'
    - 'Funding sources': 'about/funding.md'
    - 'Related projects' : 'about/related.md'
    - Infrastructure:
      - 'Jupyterhub': 'about/infrastructure/jupyterhub.md'
      - 'Installing Python packages': 'about/infrastructure/installing_python_packages.md'
      - AWS:
        - 'Getting started': 'about/infrastructure/aws/getting_started.md'
        - 'Simple Storage Service': 'about/infrastructure/aws/s3.md'
theme: mkdocs
plugins:
  - bibtex:
      bib_file: "bibliography.bib"
      cite_style: "pandoc"
