site_name: Automated Fiber Quantification
nav:
- Home: 'index.md'
- Background:
    - 'Diffusion MRI': 'background/diffusion-mri.md'
    - 'Machine learning': 'background/machine-learning.md'
    - 'Datasets': 'background/datasets.md'
- About:
    - 'License': 'about/license.md'
    - 'Funding sources': 'about/funding.md'
    - 'Related projects' : 'about/related.md'
    - 'Our projects' : 'about/projects.md'
    - 'Example: RecoBundles 80-bundle segmentation': 'about/example_recobundles_80_hcp.md'
    - 'Example: streamline density plot': 'about/example_frontal_callosum_density.md'
    - 'Team and collaborators' : 'about/team.md'
    - Infrastructure:
      - 'Jupyterhub': 'about/infrastructure/jupyterhub.md'
      - 'Installing Python packages': 'about/infrastructure/installing_python_packages.md'
      - AWS:
        - 'Getting started': 'about/infrastructure/aws/getting_started.md'
        - 'Guidelines for our projects': 'about/infrastructure/aws/how_to_use.md'
        - 'Simple Storage Service': 'about/infrastructure/aws/s3.md'
theme: gitbook
plugins:
  - bibtex:
      bib_file: "bibliography.bib"
      cite_style: "pandoc"
